name: Build UnleashedRecomp Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android dependencies
      shell: pwsh
      run: |
        sdkmanager `
          "platforms;android-35" `
          "build-tools;35.0.0" `
          "ndk;29.0.14206865" `
          "cmake;3.31.0"

    - name: Install Ninja
      shell: pwsh
      run: |
        choco install ninja -y
        echo "C:\ProgramData\chocolatey\bin" >> $env:GITHUB_PATH

    - name: Setup environment
      shell: pwsh
      run: |
        echo "ANDROID_NDK_HOME=$env:ANDROID_HOME\ndk\29.0.14206865" >> $env:GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$env:ANDROID_HOME\ndk\29.0.14206865" >> $env:GITHUB_ENV


    #
    # Build host tools
    #

    - name: Extract zstd
      shell: bash
      run: |
        rm -rf tools/XenosRecomp/thirdparty/zstd
        mkdir -p tools/XenosRecomp/thirdparty/zstd
        unzip -oq thirdparty/zstd.zip -d tools/XenosRecomp/thirdparty/zstd
        ls tools/XenosRecomp/thirdparty/zstd


    - name: Build host tools
      shell: pwsh
      run: |
        cmake --preset x64-Clang-HostTools
        cmake --build out/build/x64-Clang-HostTools


    - name: Locate host tools
      shell: pwsh
      run: |
        Get-ChildItem -Path out/build/x64-Clang-HostTools -Recurse -Filter *.exe


    #
    # vcpkg
    #

    - name: Setup vcpkg
      shell: pwsh
      run: |
            if (Test-Path vcpkg) {
               Remove-Item -Recurse -Force vcpkg
            }
                
            git clone https://github.com/microsoft/vcpkg.git vcpkg
                
            cmd /c vcpkg\bootstrap-vcpkg.bat
                
            .\vcpkg\vcpkg.exe install freetype --triplet x64-windows


    #
    # Configure Android ARM64
    #

    - name: Configure Android ARM64
      shell: pwsh
      run: |
        cmake `
          -S . `
          -B out/build/android-arm64 `
          -G Ninja `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_TOOLCHAIN_FILE="$env:ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake" `
          -DANDROID_ABI=arm64-v8a `
          -DANDROID_PLATFORM=android-23 `
          -DUNLEASHED_RECOMP_ANDROID=ON `
          -DUNLEASHED_RECOMP_HOST_XENON_RECOMP="$pwd/out/build/x64-Clang-HostTools/tools/XenonRecomp.exe" `
          -DUNLEASHED_RECOMP_HOST_XENOS_RECOMP="$pwd/out/build/x64-Clang-HostTools/tools/XenosRecomp.exe" `
          -DUNLEASHED_RECOMP_HOST_FILE_TO_C="$pwd/out/build/x64-Clang-HostTools/tools/file_to_c.exe" `
          -DUNLEASHED_RECOMP_HOST_X_DECOMPRESS="$pwd/out/build/x64-Clang-HostTools/tools/x_decompress.exe"


    #
    # Build native library
    #

    - name: Build native library
      shell: pwsh
      run: |
        cmake --build out/build/android-arm64


    #
    # Build APK
    #

    - name: Build APK
      shell: cmd
      run: |
        cd android-apk
        gradlew.bat assembleDebug


    #
    # Upload APK
    #

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: UnleashedRecomp-debug-apk
        path: |
          android-apk/app/build/outputs/apk/debug/*.apk
