name: Build UnleashedRecomp Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android dependencies
      shell: pwsh
      run: |
        sdkmanager `
          "platforms;android-35" `
          "build-tools;35.0.0" `
          "ndk;29.0.14206865" `
          "cmake;3.31.0"

    - name: Install Ninja
      shell: pwsh
      run: |
        choco install ninja -y
        echo "C:\ProgramData\chocolatey\bin" >> $env:GITHUB_PATH

    - name: Setup environment
      shell: pwsh
      run: |
        echo "ANDROID_NDK_HOME=$env:ANDROID_HOME\ndk\29.0.14206865" >> $env:GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$env:ANDROID_HOME\ndk\29.0.14206865" >> $env:GITHUB_ENV


    #
    # Build host tools
    #

    - name: Extract zstd
      shell: bash
      run: |
        rm -rf tools/XenosRecomp/thirdparty/zstd
        mkdir -p tools/XenosRecomp/thirdparty/zstd
        unzip -oq thirdparty/zstd.zip -d tools/XenosRecomp/thirdparty/zstd
        ls tools/XenosRecomp/thirdparty/zstd


    - name: Build host tools
      shell: pwsh
      run: |
        cmake --preset x64-Clang-HostTools
        cmake --build out/build/x64-Clang-HostTools --target XenonRecomp --target XenosRecomp --target file_to_c --target x_decompress


    - name: Locate host tools
      shell: pwsh
      run: |
        Get-ChildItem -Path out/build/x64-Clang-HostTools -Recurse -Filter *.exe


    #
    # Game Assets
    #
    
    - name: Fetch game assets from private assets repo
      shell: pwsh
      run: |
        $headers = @{ Authorization = "token $env:ASSETS_REPO_TOKEN" }
        
        Invoke-WebRequest `
          -Uri "https://raw.githubusercontent.com/GdGohan/Private/main/default.xex" `
          -Headers $headers `
          -OutFile "UnleashedRecompLib/private/default.xex"

        Invoke-WebRequest `
          -Uri "https://raw.githubusercontent.com/GdGohan/Private/main/default.xexp" `
          -Headers $headers `
          -OutFile "UnleashedRecompLib/private/default.xexp"

        Invoke-WebRequest `
          -Uri "https://raw.githubusercontent.com/GdGohan/Private/main/shader.ar" `
          -Headers $headers `
          -OutFile "UnleashedRecompLib/private/shader.ar"
      env:
        ASSETS_REPO_TOKEN: ${{ secrets.ASSETS_REPO_TOKEN }}

    
    #
    # vcpkg
    #

    - name: Setup vcpkg
      shell: pwsh
      run: |
            if (Test-Path vcpkg) {
               Remove-Item -Recurse -Force vcpkg
            }
                
            git clone https://github.com/microsoft/vcpkg.git vcpkg
                
            cmd /c vcpkg\bootstrap-vcpkg.bat
                
            .\vcpkg\vcpkg.exe install --triplet arm64-android --overlay-triplets=vcpkg/triplets


    #
    # Configure Android ARM64
    #

    - name: Configure Android ARM64
      shell: pwsh
      run: |
        cmake `
          -S . `
          -B out/build/android-arm64 `
          -G Ninja `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_TOOLCHAIN_FILE="$pwd/vcpkg/scripts/buildsystems/vcpkg.cmake" `
          -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="$env:ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake" `
          -DVCPKG_TARGET_TRIPLET=arm64-android `
          -DVCPKG_OVERLAY_TRIPLETS="$pwd/vcpkg/triplets" `
          -DANDROID_ABI=arm64-v8a `
          -DANDROID_PLATFORM=android-29 `
          -DUNLEASHED_RECOMP_ANDROID=ON `
          -DUNLEASHED_RECOMP_HOST_XENON_RECOMP="$pwd/out/build/x64-Clang-HostTools/tools/XenonRecomp/XenonRecomp/XenonRecomp.exe" `
          -DUNLEASHED_RECOMP_HOST_XENOS_RECOMP="$pwd/out/build/x64-Clang-HostTools/tools/XenosRecomp/XenosRecomp/XenosRecomp.exe" `
          -DUNLEASHED_RECOMP_HOST_FILE_TO_C="$pwd/out/build/x64-Clang-HostTools/tools/file_to_c/file_to_c.exe" `
          -DUNLEASHED_RECOMP_HOST_X_DECOMPRESS="$pwd/out/build/x64-Clang-HostTools/tools/x_decompress/x_decompress.exe"

        
    #
    # Build native library
    #

    - name: Build hook libs and copy all native libs into APK project
      shell: pwsh
      run: |
        cmake --build out/build/android-arm64
        cmake --build out/build/android-arm64 --target hook_impl --target main_hook --target file_redirect_hook --target gsl_alloc_hook

        New-Item -ItemType Directory -Force -Path "android-apk/app/src/main/jniLibs/arm64-v8a" | Out-Null

        Copy-Item "out/build/android-arm64/thirdparty/libadrenotools/src/hook/*.so" "android-apk/app/src/main/jniLibs/arm64-v8a/" -Force
        Copy-Item "out/build/android-arm64/UnleashedRecomp/libmain.so" "android-apk/app/src/main/jniLibs/arm64-v8a/libmain.so" -Force


    #
    # Build APK
    #

    - name: Generate custom app icon
      shell: pwsh
      run: |
        magick resources/icon.png -resize 48x48   android-apk/app/src/main/res/mipmap-mdpi/ic_launcher.png
        magick resources/icon.png -resize 72x72   android-apk/app/src/main/res/mipmap-hdpi/ic_launcher.png
        magick resources/icon.png -resize 96x96   android-apk/app/src/main/res/mipmap-xhdpi/ic_launcher.png
        magick resources/icon.png -resize 144x144 android-apk/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
        magick resources/icon.png -resize 192x192 android-apk/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
    
    - name: Build APK
      shell: cmd
      run: |
        cd android-apk
        gradlew.bat assembleDebug


    #
    # Upload APK
    #

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: UnleashedRecomp-debug-apk
        path: |
          android-apk/app/build/outputs/apk/debug/*.apk
